sudo: required
dist: trusty
language: go
before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
script:
  - go get ./...
  - go build
  - ./integration_test.sh