sudo: required
dist: trusty
language: go
branches:
  except:
  - latest
before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
script:
  - go get ./...
  - go build
  - ./integration_test.sh
before_deploy:
  - git tag -f latest
  - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh latest
  - git remote remove gh
deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: addfs
  skip_cleanup: true
  name: Automated build of master
  body: This release contains the most current version of addfs automatically compiled on every push
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    branch: master
